<a href="https://colab.research.google.com/github/yoradzasky/2025-AI-TI1B/blob/main/Ujian_Kecerdasan_Buatan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ujian Kecerdasan Buatan : Klasifikasi

## 1. Pengolahan Data

In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [27]:
df = pd.read_csv('data_pasien.csv')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            10 non-null     int64
 1   Usia          10 non-null     int64
 2   IMT           10 non-null     float64
 3   TekananDarah  10 non-null     int64
 4   Merokok       10 non-null     object
 5   Olahraga      10 non-null     object
 6   Penyakit      10 non-null     object
dtypes: float64(1), int64(3), object(3)
memory usage: 692.0+ bytes

In [29]:
df.head()

   ID  Usia   IMT  TekananDarah Merokok Olahraga Penyakit
0   1    25  22.5           120   Tidak       Ya    Tidak
1   2    50  30.1           150      Ya    Tidak       Ya
2   3    37  27.3           140   Tidak    Tidak       Ya
3   4    29  23.8           118   Tidak       Ya    Tidak
4   5    41  31.5           160      Ya    Tidak       Ya

In [30]:
print("5 data terakhir")
df.tail()

5 data terakhir

   ID  Usia   IMT  TekananDarah Merokok Olahraga Penyakit
5   6    33  26.2           130   Tidak       Ya    Tidak
6   7    55  28.9           145      Ya    Tidak       Ya
7   8    22  21.7           110   Tidak       Ya    Tidak
8   9    45  29.4           155      Ya    Tidak       Ya
9  10    31  25.6           135   Tidak       Ya    Tidak

## 2. Pembersihan Data

In [47]:
df.isnull().sum()

ID              0
Usia            0
IMT             0
TekananDarah    0
Merokok         0
Olahraga        0
Penyakit        0
dtype: int64

In [33]:
mapping = {'Ya': 1, 'Tidak': 0}
for col in ["Merokok", "Olahraga", "Penyakit"]:
    df[col] = df[col].astype(str).str.strip().map(mapping)
print(df)

   ID  Usia   IMT  TekananDarah  Merokok  Olahraga  Penyakit
0   1    25  22.5           120        0         1         0
1   2    50  30.1           150        1         0         1
2   3    37  27.3           140        0         0         1
3   4    29  23.8           118        0         1         0
4   5    41  31.5           160        1         0         1
5   6    33  26.2           130        0         1         0
6   7    55  28.9           145        1         0         1
7   8    22  21.7           110        0         1         0
8   9    45  29.4           155        1         0         1
9  10    31  25.6           135        0         1         0

## 3. Pemrosesan Data

In [34]:
print("pisahkan fitur dan LABEL")
X = df.drop(columns=['ID', 'Penyakit'])
y = df['Penyakit']

pisahkan fitur dan LABEL

In [35]:
print(" Split data 90:10")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.1, random_state=42
)

 Split data 90:10

In [36]:
print(" Normalisasi data numerik")
num_cols = ['Usia', 'IMT', 'TekananDarah']
scaler = StandardScaler()
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

 Normalisasi data numerik

## 4. Klasifikasi

In [37]:
print(" Desision Tree Classifier")
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

 Desision Tree Classifier

DecisionTreeClassifier(random_state=42)

In [39]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi Model Decision Tree: {:.2f}%".format(accuracy * 100))

Akurasi Model Decision Tree: 100.00%